[build-system]
requires = ["setuptools>=68", "wheel", "build"]
build-backend = "setuptools.build_meta"

[project]
name = "dataops-classes"
version = "0.1.0"
description = "Biblioteca para manipulação de dados com o HBase"
license = "MIT"
readme = "README.md"
authors = [
    {name = "Leonardo Jeronimo", email = "leonardo.silva@activebi.com.br"}
]
requires-python = ">=3.10"

dependencies = [
    "pandas>=2.0",
    "happybase>=1.3.0",
    "SQLAlchemy"
]

[tool.setuptools]
package-dir = { "" = "src" }
packages = { find = {} }
include-package-data = true
zip-safe = false

[tool.setuptools.packages.find]
where = ["src"]
