[metadata]
name = activebi-dataops
version = 0.1.2
description = Utilities for ActiveBI Hadoop DataOps
author = ActiveBI
license = MIT

[options]
packages = find:
python_requires = >=3.8
install_requires =
    requests>=2.25.1
    pandas>=2.0
    happybase>=1.3.0
    SQLAlchemy
    # Install a package directly from a GitHub repo (PEP 508 direct URL)
    # Replace owner/repo and branch/tag as needed, and use the package name before '@'
    # mygithubpkg @ git+https://github.com/owner/repo.git@main#egg=mygithubpkg
    # Example with a tag
    # anotherpkg @ git+https://github.com/owner/anotherpkg.git@v1.2.3#egg=anotherpkg

[options.extras_require]
dev =
    pytest
    black

# [options.packages.find]
# where = src